### ISSUE TITLE
need network generator

### ISSUE THREAD

**Issue by mgerdts** [joyent/linux-live#12]
Triton's booter will provide `networking.json`, indicating how networking should be configured.  A systemd [generator](https://www.freedesktop.org/software/systemd/man/systemd.generator.html) is needed to create the appropriate [.link](https://www.freedesktop.org/software/systemd/man/systemd.link.html) and [.network](https://www.freedesktop.org/software/systemd/man/systemd.network.html) files under `/var/systemd`.

In the absence of `networking.conf`, it should generate a generic configuration that enables dhcp on all interfaces.

**Comment by bahamat** [comment]
Fixed.
