### ISSUE TITLE
Setup Tries to put setup_complete in /var/svc

### ISSUE THREAD

**Issue by Smithx10** [joyent/linux-live#15]
[2021-10-04T19:13:33.005Z]  INFO: ur/2727 on ac-1f-6b-a4-df-ee: Publishing execute-reply to request 854ab79c-5e02-ef05-f430-c9aa5956d41c:
[2021-10-04T19:13:33.005Z]  INFO: ur/2727 on ac-1f-6b-a4-df-ee:
    {
      exit_status: 1,
      stdout: '',
      stderr: "touch: cannot touch '/var/svc/setup_complete': No such file or directory\n"
    }

**Comment by twhiteman** [comment]
Is your `cnapi` service up-to-date? As it's meant to skip that step for Linux:
https://github.com/joyent/sdc-cnapi/blob/be6cf8b7453f6ccb2b26a419999faa8c3d25e3fb/lib/workflows/server-setup.js#L225

**Comment by Smithx10** [comment]
@twhiteman  I'll update all the services and try again.  Pretty sure that's it .

**Comment by Smithx10** [comment]
after updating,  

cnapi.touch_setup_complete
OK - not needed on Linux
