### ISSUE TITLE
zfs build needs to be separated

### ISSUE THREAD

**Issue by mgerdts** [joyent/linux-live#9]
I think that for developer productivity, the existing debian-live build is on the right path.  However, we need to have a way to create a distributable PI and have a way to allow external users to build the zfs binaries easily.

The general direction I expect this to take is described at

https://github.com/joyent/linux-live/blob/929f86535e75e2deff852eb1f464e252b613300d/docs/2-platform-image.md#image-distribution

Before blindly following the direction described in that link, compare it to what is found at a similar location in the linuxcn and/or master branches.

**Comment by bahamat** [comment]
We've concluded that shipping ZFS with Linux is no more of a violation than shipping KVM with illumos. Ubuntu has also set precedent in shipping ZFS along with Linux.
